// Date: 26.05.2014 21:02:33
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package de.zsgn.industrialscience.item;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelClimbingBoots extends ModelBiped {
    // fields
    ModelRenderer shoe;
    ModelRenderer spike;

    public ModelClimbingBoots(float f) {
        super(f);
        textureWidth = 64;
        textureHeight = 64;

        shoe = new ModelRenderer(this, 0, 0);
        shoe.addBox(0F, 0F, 0F, 10, 3, 6);
        shoe.setRotationPoint(-5F, 21F, -3F);
        shoe.setTextureSize(64, 32);
        shoe.mirror = true;
        this.setRotation(shoe, 0F, 0F, 0F);
        spike = new ModelRenderer(this, 0, 0);
        spike.addBox(0F, 0F, 0F, 1, 2, 2);
        spike.setRotationPoint(2F, 21F, -5F);
        spike.setTextureSize(64, 32);
        spike.mirror = true;
        this.setRotation(spike, 0F, 0F, 0F);

        bipedLeftLeg.addChild(shoe);
        bipedRightLeg.addChild(spike);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3,
            float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        // shoe.render(f5);
        spike.render(f5);

    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
}
